### ISSUE TITLE
Request for better documentation

### ISSUE THREAD

**Issue by cjhubert** [mendelgusmao/SublimeGoCoverage#1]
Heya! I was hoping we could get better documentation on the README.md to better understand how to install and use this in Sublime. I use Sublime on OSX and seem to be unable to get any UI / options for this to appear. I've generated the cover profile using `gom test -coverprofile cover.out src/*`, but do not quite understand how to get Sublime to then read that file. Reading the documentation on the Ruby plugin hasn't given any real good hints either. Hopefully we can get this working since it seems cool, thanks!

**Comment by mendelgusmao** [comment]
Right now there are no UI options. The runners (go tools  and ginkgo supported for now) have hardcoded command lines and the parser expects a .coverprofile file in the tested package directory. I'm working right now to make it more flexible, with fully customizated command lines to not to limit to two or three test suites.

Maybe it should be a good idea to flexibilize the path to the output file, because it seems, by your example, that you are generating a giant cover profile for a lot of packages...

**Comment by cjhubert** [comment]
Hmm, I made the file `src/src.coverprofile` as that's what it looked like it was searching for after running through the python and then hit `ctrl+alt+g` but didn't see any changes. Do you know of anything I could execute in the Sublime console to see why it's not finding my file? Kind of puzzled as to why it isn't working.

**Comment by mendelgusmao** [comment]
Well... If something goes wrong when reading the cover profile, it'll tell in the console.

I'll take a look at gom when I finish the aforementioned flexibilization...

**Comment by cjhubert** [comment]
Ah, I see what you mean. I'll keep toying with things and see if I can help out. One thing that did seem strange to me is that `os.environ` doesn't contain `GOPATH` for me, the environment variables in sublime text seem completely separate from the ones on my machine. Not sure if that's supposed to be set in the sublime-options file somewhere.

**Comment by mendelgusmao** [comment]
Oh-oh... my environment variables are set in ~/.profile. Does adding a "env" config entry for setting manually gopath and others (like GoSublime does) help?

**Comment by mendelgusmao** [comment]
Hey, where do I find "gom"? (or is that a typo?)

Also, just updated the README.

**Comment by cjhubert** [comment]
You can get [gom here](https://github.com/mattn/gom)

Here's an example of how our files are laid out:

```
   bin/
   src/
     client.go
     client_test.go
     server.go
     server_test.go
   _vendor/
     (packages downloaded through gom install)
   Gomfile
```

**Comment by mendelgusmao** [comment]
Update your SublimeGoCoverage and put these lines in SublimeGoCoverage.sublime-settings:

``` json
{
    "command_line": "/path/to/gom test -coverprofile=%(cover_profile)s %(package_full_name)s",
    "cover_profile_path": "%(package_dir)s/cover.out"
}
```

I think it should work now.

**Comment by cjhubert** [comment]
After looking up in the console more, I realize it is error'ing out on the GOPATH, so I have to solve that first. I do have `export GOPATH=$HOME/go` in my `~/.bash_profile`, it's definitely set in my environment variables, but sublime text doesn't seem to load those. I'm not exactly sure how GoSublime works

**Comment by mendelgusmao** [comment]
It's because .bash_profile only applies to new sessions of bash. Does OSX have ~/.profile or something that is executed at the logon?

**Comment by cjhubert** [comment]
Ah, apparently I can do it in `/etc/launchd.conf`, trying that out.

**Comment by cjhubert** [comment]
It looks like ln 55

```
if type(cover_profile_path) is not str or len(cover_profile_path) == 0:
```

is failing for me because the type isn't str

```
>>> cover_profile_path = sublime.load_settings(settings).get("cover_profile_path")
>>> cover_profile_path
u'%(package_dir)s/%(package_name)s.coverprofile'
>>> type(cover_profile_path)
<type 'unicode'>
```

**Comment by cjhubert** [comment]
I also get this when I run it, though not sure why:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./SublimeGoCoverage.py", line 37, in run
  File "./SublimeGoCoverage.py", line 78, in run_tests
AttributeError: 'module' object has no attribute 'check_output'
```

**Comment by mendelgusmao** [comment]
Which Python version is yours?

**Comment by cjhubert** [comment]
Ugh, python versioning is a mess on OSX since it installs all sorts of versions itself. According to Sublime console:

```
>>> import sys
>>> sys.version_info
(2, 6, 8, 'final', 0)
```

Which is odd since just a normal shell says

```
$ python --version
Python 2.7.5
```

**Comment by mendelgusmao** [comment]
unicode + check_output solved.

**Comment by cjhubert** [comment]
:confused: seem to be stuck at this point:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 362, in run_
  File "./SublimeGoCoverage.py", line 37, in run
  File "./SublimeGoCoverage.py", line 85, in run_tests
UnboundLocalError: local variable 'handler' referenced before assignment
```

Which is just it saying it can't run the tests anyways. The handler try (ln 75, where it tries to do Popen) seems to be outputting this, which I don't really have any ideas on

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
TypeError: execv() argument 1 must be encoded string without NULL bytes, not str
```

**Comment by mendelgusmao** [comment]
The first one is already fixed. I'll take a look at the second.

**Comment by mendelgusmao** [comment]
Tomorrow I'll be borrowing a Macbook and installing ST to better understand what's going on.

**Comment by cjhubert** [comment]
Thanks so much for all your help! I _think_ I got it working by changing it to `encode('ascii')` based on some googling. So now, no errors when I run it, but still doesn't highlight lines. I'll keep trying things out on my end.

``` python
cmd = command_line % file_info
handler = subprocess.Popen(
    shlex.split(cmd.encode('ascii')),
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT)
output = handler.communicate()[0]
```

**Comment by mendelgusmao** [comment]
I tried this one but it didn't work here (Ubuntu 14.04)

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 549, in run_
    return self.run(edit)
  File "SublimeGoCoverage in /home/mendelson/.config/sublime-text-3/Installed Packages/SublimeGoCoverage.sublime-package", line 37, in run
  File "SublimeGoCoverage in /home/mendelson/.config/sublime-text-3/Installed Packages/SublimeGoCoverage.sublime-package", line 81, in run_tests
  File "./shlex.py", line 276, in split
  File "./shlex.py", line 266, in __next__
  File "./shlex.py", line 93, in get_token
  File "./shlex.py", line 121, in read_token
AttributeError: 'bytes' object has no attribute 'read'
```

**Comment by cjhubert** [comment]
Ah ha! Finally got it working on mac. My changes include the one I listed above (`.encode('ascii')`) as well as the following. This line wasn't working for me:

``` python
if line["count"] == "0" and view.file_name().endswith(line["filename"]):
```

Because the coverprofile as written out by Go for me looks something like this:

```
command-line-arguments/client.go:20.26,22.22 1 1
command-line-arguments/client.go:31.2,31.18 1 1
command-line-arguments/client.go:22.22,30.3 3 1
command-line-arguments/client.go:36.71,42.2 5 0
```

So the `.endswith` doesn't come back as true. Changing it to this worked:

``` python
filename = line["filename"].split('/', 1)[-1]
if line["count"] == "0" and view.file_name().endswith(filename):
```

Let me know your thoughts, obviously wouldn't want to break it for Windows or other installers so my methods might not be the best.

**Comment by mendelgusmao** [comment]
Well, the .encode trick is not behaving well with my ST (3; uses Python 3.3.3). I'll take a look at the code of other packages to learn how they deal with portability.

I don't know for sure how to solve the issue with the filenames. Does running the tests using "go test" change the filenames in the cover profile?

**Comment by cjhubert** [comment]
Nope, go test also outputs the file with `command-line-arguments`

**Comment by mendelgusmao** [comment]
I'm a bit confused about what `command-line-arguments` represents. Is it some kind of placeholder you used to shorten information or it's a real directory name? Is it something like `$GOPATH/src/command-line-arguments/client.go`?

**Comment by cjhubert** [comment]
Oh, no, I don't _think_ it has anything to do with me as far as I know. I thought it was a built-in package of go. Even when I run go test it says: `ok     command-line-arguments  0.007s  coverage: 68.4% of statements`

I confirmed it acts the same both on OSX and Ubuntu 14.04 (adding command-line-arguments/ before the name of files). My file structure is exactly as I mentioned above, with `.go` files in `/src/`. No other folders in `/src/`
